### ISSUE TITLE
Create Health(HP) System

### ISSUE THREAD

**Issue by dmashuda** [awesomegroupidunno/senior-design#16]

**Comment by aforry** [comment]
As part of my Vehicle class I included an int variable for endurance, i.e. player HP.  The general idea being GameState can pass each players Vehicle to the server.  This will include, but isn't limited to: xy coordinates, forward facing angle, current velocity, etc.

Not sure if this handles this issue already or not, we can talk about it in class tomorrow. I have these changes in a separate branch in game-client for now, master hasn't been updated.

**Comment by dmashuda** [comment]
This refers to actually implementing a whole health system, not just having fields in the Vehicle class.

so this will be deferred till the 50%, because the minimal working system will be to just drive a car around
