### ISSUE TITLE
Establish standard for communication between client and server

### ISSUE THREAD

**Issue by dmashuda** [awesomegroupidunno/senior-design#2]
- UDP is a given, but how to do this most effectively?

**Comment by dmashuda** [comment]
Interesting article:
http://gafferongames.com/2015/09/12/is-it-just-me-or-is-networking-really-hard/

**Comment by numberQ** [comment]
I suddenly understand so much about networking. The way the article describes, it doesn't conceptually seem too hard to implement.

**Comment by dmashuda** [comment]
I agree, It points to bundling and resending old info til an ack is returned.

**Comment by dmashuda** [comment]
As far as format of the info:
I think that JSON is the way to go, because it is fairly simple to parse.
And a command-based system should be used for integration:

command = {
"command_type": "accelerate",
"value": 4,
}

command = {
"command_type": "turn",
"direction": "cw",
"value": 4,
}

these are rough ideas, but the concept is there:
we can transmit a json array of "commands" to the server. 

The server can respond with the latest gameState

**Comment by numberQ** [comment]
That looks pretty nice actually. We were also wondering about receiving network info to the client, since we don't have a lot of that kind of experience. We had the idea of a NetworkController or NetworkReceiver class that would take the server's packets, parse them, and tell the game state what to change.

**Comment by dmashuda** [comment]
I think to start, we should just return a full copy of the gamestate to the client; the client just accepts the current gamestate and keeps going. Just to see what kind of performance we are getting. 

If we need better performance, we can compute the delta's(changes) for the clients and send the deltas over the network to the client. Then update the client's gamestate that way. 

Computing the delta's seems to be a more efficient way of transmitting data, but let's start with the more simple solution to start.

**Comment by numberQ** [comment]
Okay, I agree with starting like that.

**Comment by numberQ** [comment]
Do you think this can be closed @dmashuda? Just so it's here, our standard at the moment is as such:

{
"Type": (string) (almost always "POST")
"Subtype": (string) ("CONNECT" / "ACCELERATE" / "TURN" / etc)
"IntValue": (int) (moving forwards or backwards, turning left or right, etc)
"StrValue": (string) (username when connecting, ID of target car for lock-on attacks, etc)
}

**Comment by dmashuda** [comment]
@numberQ: This accounts for numbers that are not integers
{
"Type": (string) (almost always "POST")
"Subtype": (string) ("CONNECT" / "ACCELERATE" / "TURN" / etc)
"NumValue": (number) (moving forwards or backwards, turning left or right, etc)
"StrValue": (string) (username when connecting, ID of target car for lock-on attacks, etc)
}

**Comment by dmashuda** [comment]
this issue is now resolved
