### ISSUE TITLE
Create Basic command set

### ISSUE THREAD

**Issue by dmashuda** [awesomegroupidunno/senior-design#3]
commands for clients to send to server for gamestate to be changed

**Comment by numberQ** [comment]
@austin4e and I were discussing how the client and server will communicate car info, i.e., position, turn angle, etc. We said that each client would send a JSON object containing the updated info for only that client's car, and the server would apply appropriate calculations (collision detection, etc), then send a JSON object containing an array of every car's new info. Thoughts on that?

**Comment by dmashuda** [comment]
Completed: https://github.com/awesomegroupidunno/game-server/commit/d1f44ba90277dff912d774d21d6c35e079e22923
