### ISSUE TITLE
Implement update() method

### ISSUE THREAD

**Issue by numberQ** [awesomegroupidunno/senior-design#34]
When the Listener class receives a message, it should call update() on the Client, which should in turn decode the server's message and pass a new GameState to the Controller

**Comment by numberQ** [comment]
This is partially implemented - decode() doesn't return a GameState yet.

**Comment by dmashuda** [comment]
Is this completed?

**Comment by numberQ** [comment]
decode() returns a proper GameState now. This will continuously be updated as we add more to our GameState, but the issue will be closed anyway.
